create table item (
  id int unsigned primary key auto_increment not null,
  title varchar(255) not null
);


insert into item (title) values ("Title1"), ("Title2"), ("Title3");

CREATE TABLE article (
    id INT NOT NULL AUTO_INCREMENT primary key, 
    name VARCHAR(100) NOT NULL,
    author VARCHAR(100) NOT NULL,
    title VARCHAR(150) NOT NULL,
    description TEXT NOT NULL,
    url VARCHAR(150) NOT NULL,
    urlToImage VARCHAR(255) NOT NULL,
    publishedAt VARCHAR(100) NOT NULL
);

INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Tage Kene-okafor','African VC firm Enza Capital launches founder partner program as it closes $58M across funds | TechCrunch','Enza Capital has closed $58 million across two funds and launched its founder partner program where founders become co-owners in the firm.','https://techcrunch.com/2023/09/28/african-vc-firm-enza-capital-launches-founder-partner-program-as-it-closes-funds-at-58m/','https://techcrunch.com/wp-content/uploads/2023/09/98794DF0-EBE0-4D5D-8AAD-62F0ACE37814.jpeg?w=1170','2023-09-28T07:07:30Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Amanda Silberling','X will be profitable in 2024, CEO claims in tense interview','According to X CEO Linda Yaccarino, the company formerly known as Twitter will be profitable by early 2024.  "Now that I have immersed myself in the business...','https://techcrunch.com/2023/09/27/x-will-be-profitable-in-2024-ceo-claims-in-tense-interview/','https://s.yimg.com/ny/api/res/1.2/gzyx8TCIA2bGCNF4NJOfmQ--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD05MTY-/https://media.zenfs.com/en/techcrunch_350/0192ce716fe27f9abbbcc9837491cf85','2023-09-28T01:58:08Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Taylor Hatmaker','Epic asks the Supreme Court to weigh in on its beef with Apple','Epic Games filed a cert petition with the Supreme Court on Wednesday, setting things in motion for the highest court in the land to reexamine if Apple''s...','https://techcrunch.com/2023/09/27/epic-asks-the-supreme-court-to-weigh-in-on-its-beef-with-apple/','https://media.zenfs.com/en/techcrunch_350/55b8207e5bb2db408c31bcef2147556e','2023-09-28T00:56:35Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Ingrid Lunden','Meta filmed Mr Beast, Paris Hilton and 26 more to build celebrity AIs based on Llama 2 | TechCrunch','Meta filmed Mr Beast, Paris Hilton and 26 more to build celebrity AIs based on Llama 2 | TechCrunchtechcrunch.com','https://techcrunch.com/2023/09/27/meta-mr-beast-paris-hilton-celebrity-ais-llama-2/','https://techcrunch.com/wp-content/uploads/2023/09/snoop-dogg-dungeon-master.jpg?w=1032','2023-09-27T20:34:11Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Rebecca Bellan','Can Bird''s Spin acquisition give it the lift it needs? | TechCrunch','Back in the scooter craze days of 2019, Bird was valued at a whopping $2.5 billion.','https://techcrunch.com/2023/09/27/bird-spin-acquisition-will-it-help/','https://techcrunch.com/wp-content/uploads/2019/06/GettyImages-1149449644.jpg?resize=1200,798','2023-09-27T20:01:10Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Kyle Wiggers','Meta parties like it''s 2015, brings new chatbots to its messaging apps | TechCrunch','Meta has introduced a range of new chatbots that can be invoked through its messaging apps, including Instagram and Messenger.','https://techcrunch.com/2023/09/27/meta-parties-like-its-2015-brings-new-chatbots-to-its-messaging-apps/','https://techcrunch.com/wp-content/uploads/2021/11/facebook-meta-rough-texture.jpg?resize=1200,675','2023-09-27T19:21:53Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Devin Coldewey','Mistral AI makes its first large language model free for everyone | TechCrunch','Mistral, a French AI startup that raised a huge seed round in June, has debuted its first model, totally free to download and use.','https://techcrunch.com/2023/09/27/mistral-ai-makes-its-first-large-language-model-free-for-everyone/','https://techcrunch.com/wp-content/uploads/2023/09/mistral-7b-v0.1.jpg?resize=1200,610','2023-09-27T18:41:50Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Aisha Malik','Roblox is launching on Meta Quest VR headsets today','The announcement comes as Roblox, a major player in the metaverse space, was rumored to become available on Meta Quest VR headsets sometime this year.  Meta ...','https://techcrunch.com/2023/09/27/roblox-is-launching-on-meta-quest-vr-headsets-today/','https://s.yimg.com/ny/api/res/1.2/jiJNT.rM4JJ7O49e7lehgQ--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD02NjI-/https://media.zenfs.com/en/techcrunch_350/119871c85197e0065b849bba2437f605','2023-09-27T17:53:26Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Kyle Wiggers','Workday unveils new HR-focused generative AI features | TechCrunch','At its annual Workday Rising conference, Workday announced a host of new HR-oriented generative AI features.','https://techcrunch.com/2023/09/27/workday-unveils-new-hr-focused-generative-ai-features/','https://techcrunch.com/wp-content/uploads/2018/02/tc-backlight.png?resize=1200,486','2023-09-27T17:16:05Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Sarah Perez','Warner Music CEO Robert Kyncl says AI to impact the music industry within the next year | TechCrunch','Warner Music CEO Robert Kyncl believes AI will be significantly impacting the music industry within the next year. Speaking at the Code Conference this','https://techcrunch.com/2023/09/27/warner-music-ceo-robert-kyncl-says-ai-to-impact-the-music-industry-within-the-next-year/','https://techcrunch.com/wp-content/uploads/2023/09/1703197251.jpg?resize=1200,800','2023-09-27T16:53:22Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Kyle Wiggers','Rollstack automatically syncs data to reports and presentations | TechCrunch','Rollstack, a startup backed by Y Combinator, among others, has raised cash for its platform that syncs data to presentations and reports.','https://techcrunch.com/2023/09/27/rollstack-automatically-syncs-data-to-reports-and-presentations/','https://techcrunch.com/wp-content/uploads/2022/09/GettyImages-1388002888.jpg?resize=1200,800','2023-09-27T15:01:21Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Sarah Perez','Walmart returns to Roblox after its first games were attacked by consumer advocacy groups | TechCrunch','Walmart is returning to Roblox, but this time with a virtual world where gamers can discover new virtual items and accessories to personalize their','https://techcrunch.com/2023/09/27/walmart-returns-to-roblox-after-its-first-games-were-attacked-by-consumer-advocacy-groups/','https://techcrunch.com/wp-content/uploads/2023/09/Walmart-Discovered-on-Roblox.jpg?resize=1200,675','2023-09-27T14:06:49Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Romain Dillet','La Belle Vie acquires Frichti following bankruptcy process | TechCrunch','French grocery delivery startup La Belle Vie is acquiring Frichti, another food delivery service that was placed under receivership.','https://techcrunch.com/2023/09/27/la-belle-vie-acquires-frichti-following-bankruptcy-process/','https://techcrunch.com/wp-content/uploads/2023/09/GettyImages-1302634417.jpg?resize=1200,800','2023-09-27T13:50:20Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Natasha Lomas','Elon Musk''s X removes general option to report misleading info about politics','X (formerly Twitter) appears to have removed an option that allowed users in a handful of markets to directly report misleading information about politics.  ...','https://techcrunch.com/2023/09/27/x-limits-report-post-options/','https://s.yimg.com/ny/api/res/1.2/cDfbFUmcNDefoG_7eZINig--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD04NTg-/https://media.zenfs.com/en/techcrunch_350/9fe311e78704f128095490abab8ed098','2023-09-27T13:26:27Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Carrie Andrews','Fintech actually has a value system: Here’s how we can reclaim it','One of the big lessons of the social finance backlash is that empowerment without education can do more harm than good.','https://techcrunch.com/2023/09/27/fintech-actually-has-a-value-system-heres-how-we-can-reclaim-it/','https://techcrunch.com/wp-content/uploads/2023/09/GettyImages-76186554.jpg?resize=1200,788','2023-09-27T13:00:45Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Ivan Mehta','Former Tinder CEO''s startup to fight loneliness with AI chatbot gets backing by Sequoia | TechCrunch','Former Tinder CEO Renate Nyborg''s startup Meeno, said Thursday that it has raised a $3.9 million seed round led by Sequoia.','https://techcrunch.com/2023/09/27/former-tinder-ceos-startup-to-fight-loneliness-with-ai-chatbot-gets-backing-by-sequoia/','https://techcrunch.com/wp-content/uploads/2023/09/Meeno.jpeg?resize=1200,907','2023-09-27T12:38:12Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Frederic Lardinois','Senser launches its AI-enhanced observability platform, raises $9.5M | TechCrunch','Senser describes itself as an AIOps platform that uses machine learning to help developers and ops teams more easily get to the root causes of outages and','https://techcrunch.com/2023/09/27/senser-launches-its-ai-enhanced-observability-platform-raises-9-5m/','https://techcrunch.com/wp-content/uploads/2023/09/GettyImages-1367730906.jpg?resize=1200,775','2023-09-27T12:08:38Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Frederic Lardinois','Akamai launches new cloud computing regions in Asia, Europe and the Americas | TechCrunch','Akamai expands its cloud computing reach with new global regions, leveraging its edge network to offer low-latency cloud computing services.','https://techcrunch.com/2023/09/27/akamai-launches-new-cloud-computing-regions-in-asia-europe-and-the-americas/','https://techcrunch.com/wp-content/uploads/2023/09/GettyImages-1242472226-Large.jpg?resize=1200,800','2023-09-27T10:32:03Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Tage Kene-okafor','QED and Partech back South African payment orchestration platform Revio in $5.2M seed | TechCrunch','Payment orchestration platform Revio raises $5.2 million to reduce the cost, risk and complexity of payment operations in Africa.','https://techcrunch.com/2023/09/27/qed-and-partech-back-south-african-payment-orchestration-platform-revio-in-5-2m-seed/','https://techcrunch.com/wp-content/uploads/2023/09/4C7E45D4-CD5F-46AA-8517-8850ED4C88D2.jpeg?w=1170','2023-09-27T09:04:00Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Mike Butcher','New research: Vast majority of VC-backed UK startups do *nothing* on climate emissions | TechCrunch','Some 76% of the top 500 VC-backed UK startups have done nothing to either measure or offset their carbon emissions, according to new research shared','https://techcrunch.com/2023/09/27/new-research-vast-majority-of-vc-backed-uk-startups-do-nothing-on-climate-emissions/','https://techcrunch.com/wp-content/uploads/2022/07/GettyImages-520529984.jpg?resize=1200,800','2023-09-27T07:36:09Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Haje Jan Kamps','Atlassian CTO: We were late moving to the cloud, on the ball with AI','“I''m responsible for all of engineering at Atlassian,” Rajeev Rajan said in our interview onstage at TechCrunch Disrupt last week.  Atlassian created a...','https://techcrunch.com/2023/09/26/atlassian-ai/','https://s.yimg.com/ny/api/res/1.2/VrXReR3LN_9GUucMhMTAbA--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD03NDU-/https://media.zenfs.com/en/techcrunch_350/f04aae38c2a3340f8e3ef4274254a83a','2023-09-26T23:31:06Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Ingrid Lunden','Sources: Palo Alto in advanced talks to buy Talon and Dig in a $1B security sweep | TechCrunch','Palo Alto Networks'' stock price has been on the rise on the back of strong earnings and growing demand for cybersecurity services, and now the company is','https://techcrunch.com/2023/09/26/palo-alto-networks-dig-talon/','https://techcrunch.com/wp-content/uploads/2023/06/GettyImages-1300897309.jpg?resize=1200,675','2023-09-26T22:45:21Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Aria Alamalhodaei','Sierra Space raises $290M at a $5.3B valuation | TechCrunch','Sierra Space has raised $290 million in a Series B round to scale its Dream Chaser spaceplane and commercial space station projects.','https://techcrunch.com/2023/09/26/sierra-space-raises-290m-at-a-5-3b-valuation/','https://techcrunch.com/wp-content/uploads/2023/09/Sierra-Space-2023_IMAGE.jpg?resize=1200,738','2023-09-26T18:22:50Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Walter Thompson','TechCrunch+ Roundup: Slashing SaaS costs, FedNow''s ''game changer,'' diverse cap tables','In a TC+ column that includes spending benchmarks (based on employee size), CloudEagle founder and CEO Nidhi Jain shares her “cost-optimization playbook” for...','https://techcrunch.com/2023/09/26/techcrunch-roundup-slashing-saas-costs-fednows-game-changer-diverse-cap-tables/','https://s.yimg.com/ny/api/res/1.2/YDZMDHJmP5TyLRlGXOWzLg--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD04MDI-/https://media.zenfs.com/en/techcrunch_350/295c7b672a3e5ee03bf0990d60bd3e22','2023-09-26T17:34:06Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Taylor Hatmaker','The FTC just hit Amazon with a major antitrust lawsuit','The Federal Trade Commission made its big move against online shopping giant Amazon on Tuesday, accusing the company of illegally stifling competition on its...','https://techcrunch.com/2023/09/26/the-ftc-just-hit-amazon-with-a-major-antitrust-lawsuit/','https://s.yimg.com/ny/api/res/1.2/JGHc3SRmeBj74ocCsF35qQ--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD04MDA-/https://media.zenfs.com/en/techcrunch_350/2a4659a1993b69bedd907bcc2819eee1','2023-09-26T16:32:46Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Sarah Perez','Photo-sharing app Lapse hits top of the App Store by forcing you to invite your friends | TechCrunch','Forget invite-only social apps, Lapse is testing a new technique to acquire its users: it forces you to invite your friends in order to get in. The','https://techcrunch.com/2023/09/26/photo-sharing-app-lapse-hits-top-of-the-app-store-by-forcing-you-to-invite-your-friends/','https://techcrunch.com/wp-content/uploads/2023/09/lapse-header.jpeg?resize=1200,631','2023-09-26T15:53:56Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Carly Page','Why the public sector is an easy target for ransomware | TechCrunch','Fighting back against ransomware or extortion is no easy task. Two leading security experts explain what local and state governments can do.','https://techcrunch.com/2023/09/26/ransomware-public-sector-fight-back/','https://techcrunch.com/wp-content/uploads/2023/09/53206762487_f6586438b9_k.jpg?resize=1200,800','2023-09-26T14:01:35Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Sarah Perez','Google Podcasts to shut down in 2024 with listeners migrated to YouTube Music | TechCrunch','Google announced this morning it will be shutting down its Google Podcasts app later in 2024 as part of its broader transition to move its streaming','https://techcrunch.com/2023/09/26/google-podcasts-to-shut-down-in-2024-with-listeners-migrated-to-youtube-music/','https://techcrunch.com/wp-content/uploads/2019/09/GettyImages-1079623010.jpg?resize=1200,799','2023-09-26T13:45:02Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Kyle Wiggers','Series, which aims to replace ERP systems, lands $25M','Brexton Pham, Daniel Lai and Tamby Kojak -- co-founded Series, a startup launching its platform widely today.  Backed by $25 million in funding across seed...','https://techcrunch.com/2023/09/26/series-which-aims-to-replace-erp-systems-lands-25m/','https://s.yimg.com/ny/api/res/1.2/RQaBdUo7HTT_CXcDHsWI5Q--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD04MDA-/https://media.zenfs.com/en/techcrunch_350/635b811e0ac4d416ab55a80a24c17670','2023-09-26T13:00:32Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Kyle Wiggers','Erudit raises $10M to monitor workplaces for ''misalignment''','According to one poll, searches for staff monitoring software rose by 75% in March 2020 compared with the 2019 monthly average -- and demand remained strong ...','https://techcrunch.com/2023/09/26/erudit-raises-10m-to-monitor-workplaces-for-misalignment/','https://s.yimg.com/ny/api/res/1.2/sSWRBVZZBzR7fQk1srlcbg--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD04MDA-/https://media.zenfs.com/en/techcrunch_350/647bfee4be2323416d20c4640d40f023','2023-09-26T12:00:23Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Rita Liao','Telegram starts to look like a super app, echoing WeChat | TechCrunch','Telegram, the popular messenger with 800 million monthly active users worldwide, is inching closer to adopting an ecosystem strategy that is reminiscent','https://techcrunch.com/2023/09/25/telegram-wechat-super-app-ton-foundation/','https://techcrunch.com/wp-content/uploads/2021/01/GettyImages-503572806.jpg?resize=1200,854','2023-09-26T03:54:19Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Kirsten Korosec','Ford halts work on $3.5B EV battery factory with China''s CATL | TechCrunch','Ford immediately paused work at a $3.5 billion factory that was supposed to make cheaper batteries using tech from China''s CATL.','https://techcrunch.com/2023/09/25/ford-halts-work-on-3-5b-ev-battery-factory-with-chinas-catl/','https://techcrunch.com/wp-content/uploads/2022/06/Rouge-Electric-Vehicle-Center_02.jpeg?resize=1200,900','2023-09-25T23:04:32Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Devin Coldewey','Signal''s Meredith Whittaker: AI is fundamentally ''a surveillance technology''','Why is it that so many companies that rely on monetizing the data of their users seem to be extremely hot on AI?  If you ask Signal president Meredith...','https://techcrunch.com/2023/09/25/signals-meredith-whittaker-ai-is-fundamentally-a-surveillance-technology/','https://s.yimg.com/ny/api/res/1.2/RvqGip0bKqNcYUdoKM9MSg--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD04MDA-/https://media.zenfs.com/en/techcrunch_350/373ffb46ffaf8f0f6e5f00960d06cebb','2023-09-25T23:01:13Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Haje Jan Kamps','''Nobody has lost their job because of what we do,'' says CEO of film industry AI tool | TechCrunch','“Honestly, and I really can say this with a straight face, we create jobs. Because there''s so much shit to do to actually put these use cases into','https://techcrunch.com/2023/09/25/ai-writers-strike-film-industry/','https://techcrunch.com/wp-content/uploads/2023/09/Ofir-Krakowski-deepdub.ai_.jpg?resize=1200,800','2023-09-25T18:43:08Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Alex Wilhelm','The recent tech IPOs are flirting with negative territory | TechCrunch','Klaviyo and Instacart''s shares went on to trade above their initial IPO pricing after Arm''s own listing. However, the momentum hasn''t lasted long.','https://techcrunch.com/2023/09/25/the-recent-tech-ipos-are-flirting-with-negative-territory/','https://techcrunch.com/wp-content/uploads/2023/07/GettyImages-1400003953.jpg?resize=1200,768','2023-09-25T17:15:56Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Amanda Silberling','Reddit will start paying you real money for your karma | TechCrunch','Reddit announced a contributor program on Monday, which awards users actual, real money for their fake internet points. Now, eligible users will be able','https://techcrunch.com/2023/09/25/reddit-will-start-paying-you-real-money-for-your-karma/','https://techcrunch.com/wp-content/uploads/2019/03/reddit.jpg?w=1024','2023-09-25T17:12:55Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Lorenzo Franceschi-bicchierai','Hackers steal $200 million from crypto company Mixin | TechCrunch','Hong Kong-based crypto company Mixin announced it was breached, with hackers stealing around $200 million.','https://techcrunch.com/2023/09/25/hackers-steal-200-million-from-crypto-company-mixin/','https://techcrunch.com/wp-content/uploads/2023/09/crypto-hack-mixin.jpg?resize=1200,800','2023-09-25T17:11:51Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Dominic-madori Davis','What''s the best way to run a startup in a world full of advice? | TechCrunch','There exist a myriad of answers to the question, "How do you found your first startup?" But which of those answers apply to you and your situation?','https://techcrunch.com/2023/09/25/whats-the-best-way-to-run-a-startup-in-a-world-full-of-advice/','https://techcrunch.com/wp-content/uploads/2023/09/53203789168_8b8a696266_k.jpg?resize=1200,800','2023-09-25T16:01:09Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Kyle Wiggers','Nx lands $16M to build ''monorepo'' tools for software devs','Nx, a startup developing tooling to make it simpler for software dev teams to work within a single code repository, today closed a $16 million Series A round...','https://techcrunch.com/2023/09/25/nx-lands-16m-to-build-monorepo-tools-for-software-devs/','https://s.yimg.com/ny/api/res/1.2/6SEHsRYD8eedCzS_rQRTAA--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD02MTM-/https://media.zenfs.com/en/techcrunch_350/b5004c8ab82217f2d3a8d805910fd07d','2023-09-25T16:00:58Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Zack Whittaker','Decade of newborn child registry data stolen in MOVEit mass-hack | TechCrunch','The breach affecting more than 3.4 million people — including newborns and children — is one of the biggest MOVEit-related hacks of the year.','https://techcrunch.com/2023/09/25/decade-of-newborn-child-registry-data-stolen-in-moveit-mass-hack/','https://techcrunch.com/wp-content/uploads/2023/09/moveit-ontario-hack-children-getty.jpg?resize=1200,752','2023-09-25T15:57:41Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Rebecca Szkutak','The current labor market is a gold mine of talent for startups | TechCrunch','The whiplash we''ve seen in the labor market over the last few years has created an environment that startups can and should take advantage of.','https://techcrunch.com/2023/09/25/the-current-labor-market-is-a-gold-mine-of-talent-for-startups/','https://techcrunch.com/wp-content/uploads/2023/08/GettyImages-1406585619.jpg?resize=1200,800','2023-09-25T15:02:51Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Sarah Perez','Tinder snobs can now pay $499 per month to be matched with the ''most-sought after'' profiles | TechCrunch','Tinder has rolled out its promised high-end membership, a pricey $499 per month subscription dubbed "Tinder Select," which includes unique perks like the','https://techcrunch.com/2023/09/25/tinder-snobs-can-now-pay-499-per-month-to-be-matched-with-the-most-sought-after-profiles/','https://techcrunch.com/wp-content/uploads/2019/04/tinder-icon-ios.jpg?resize=1200,675','2023-09-25T14:15:19Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Paul Sawers','OpenAI gives ChatGPT a voice for verbal conversations | TechCrunch','ChatGPT is evolving into more than a text-based search engine, with OpenAI announcing that it''s adding new voice and image smarts to the mix.','https://techcrunch.com/2023/09/25/openai-chatgpt-voice/','https://techcrunch.com/wp-content/uploads/2023/09/GettyImages-1574154948-e1695647511123.jpg?resize=1200,676','2023-09-25T13:55:11Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Manish Singh','Amazon to invest up to $4 billion in AI startup Anthropic','Amazon has agreed to invest up to $4 billion in the AI startup Anthropic as the e-commerce group steps up rivalry against Microsoft, Meta, Google and Nvidia ...','https://techcrunch.com/2023/09/25/amazon-to-invest-up-to-4-billion-in-ai-startup-anthropic/','https://s.yimg.com/ny/api/res/1.2/3b0p3CM_hla1m9lW70Zbuw--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD02NzU-/https://media.zenfs.com/en/techcrunch_350/d554c9ae8b521e6447400504b0f0f3cb','2023-09-25T07:10:49Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Natasha Lomas','Correcto grabs $7M to build out its ''Grammarly for Spanish''','The generative AI boom has put a spring in the step of Correcto, a Madrid-based language writing tool startup focused on Spanish speakers that''s today...','https://techcrunch.com/2023/09/24/correcto-seed/','https://s.yimg.com/ny/api/res/1.2/lWHCh.QVbkWu39rbfB.4Yg--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD04MDA-/https://media.zenfs.com/en/techcrunch_350/c2197f971ddf812b763d2f501e489e24','2023-09-25T05:00:38Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Rebecca Bellan','California governor vetoes bill to ban driverless AV trucks | TechCrunch','California Gov. Gavin Newsom vetoed a bill Friday that would have required a human safety operator to be present any time a self-driving truck operated on','https://techcrunch.com/2023/09/24/california-governor-vetoes-bill-to-ban-driverless-av-trucks/','https://techcrunch.com/wp-content/uploads/2019/09/GettyImages-1168450645.jpg?w=1024','2023-09-25T00:17:42Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Kirsten Korosec','A conversation with Cruise''s Kyle Vogt, Bird scoops up Spin, and self-driving trucks live to see another day in Cali','A conversation with Cruise''s Kyle Vogt, Bird scoops up Spin, and self-driving trucks live to see another day in Calitechcrunch.com','https://techcrunch.com/2023/09/24/a-conversation-with-cruises-kyle-vogt-bird-scoops-up-spin-and-self-driving-trucks-live-to-see-another-day-in-cali/','https://techcrunch.com/wp-content/uploads/2023/09/53202357088_0cc74eda92_k.jpg?resize=1200,800','2023-09-24T21:56:34Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Rebecca Szkutak','Building an equitable cap table puts more tools in a startup''s toolbox | TechCrunch','Building an equitable cap table allows startups to bring on experts they wouldn''t be able to hire while making VC more diverse.','https://techcrunch.com/2023/09/24/equitable-cap-table-tools/','https://techcrunch.com/wp-content/uploads/2023/09/53203664808_585b9bdbbd_k.jpg?resize=1200,800','2023-09-24T15:04:14Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Kyle Wiggers','Elon Musk threatens to charge for X, OpenAI launches DALL-E 3 and Cisco acquires Splunk | TechCrunch','In this edition of Week in Review (WiR), we cover Elon Musk threatening to charge for X, OpenAI launching DALL-E 3 and Cisco acquiring Splunk.','https://techcrunch.com/2023/09/23/elon-musk-threatens-to-charge-for-x-openai-launches-dall-e-3-and-cisco-acquires-splunk/','https://techcrunch.com/wp-content/uploads/2023/07/x-logo-beheads-twitter-logo.jpg?resize=1200,675','2023-09-23T20:15:59Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Anna Heim','Disability tech startups kill the cynic in me | TechCrunch','"Accessibility is a human right," reads a sticker from the Howe Innovation Center. And for sure, it is great to see startups help companies make this a reality.','https://techcrunch.com/2023/09/23/disability-tech-startup-battlefield/','https://techcrunch.com/wp-content/uploads/2023/09/Revolve_wheelchair_Airport_folded_and_unfolded_Revolve_Mobility.jpg?resize=1200,800','2023-09-23T17:00:41Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Rita Liao','AquaLith might have an answer to the US battery material shortage problem | TechCrunch','AquaLith looks to make new types of battery cell components that don''t rely on the scarce metals normally used in lithium-ion battery packs.','https://techcrunch.com/2023/09/22/aqualith-might-have-an-answer-to-the-us-battery-material-shortage-problem/','https://techcrunch.com/wp-content/uploads/2021/02/GettyImages-154908090.jpg?resize=1200,800','2023-09-22T19:37:27Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Haje Jan Kamps','Bay Area baby belly beholding Battlefield bounty | TechCrunch','This week, the TechCrunch team descended on San Francisco’s Moscone Center to celebrate one of the biggest to-dos in the startup world: TechCrunch Disrupt.','https://techcrunch.com/2023/09/22/bay-area-baby-belly-beholding-battlefield-bounty/','https://techcrunch.com/wp-content/uploads/2023/09/20230921-DSC02586.jpg?resize=1200,800','2023-09-22T19:05:33Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Devin Coldewey','Unity U-turns on controversial runtime fee and begs forgiveness | TechCrunch','Unity has done a 180 on a controversial new pricing scheme that users of its cross-platform game engine almost unanimously disparaged.','https://techcrunch.com/2023/09/22/unity-u-turns-on-controversial-runtime-fee-and-begs-forgiveness/','https://techcrunch.com/wp-content/uploads/2023/09/unity-logo.jpeg?resize=1200,675','2023-09-22T18:55:21Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Zack Whittaker','Yes, you have to update your Apple devices again, because spyware is bad','Apple on Thursday released urgent security updates for iPhones, iPads, Macs, Apple Watch, and Safari users to patch against three vulnerabilities that Apple says are being actively exploited. The three vulnerabilities include a flaw in WebKit, the browser eng…','https://techcrunch.com/2023/09/22/update-apple-devices-pegasus-predator-spyware/','https://techcrunch.com/wp-content/uploads/2019/09/iphone_11_pro.jpg?resize=1200,695','2023-09-22T17:40:04Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Jacquelyn Melinek','Chris Lehane: The SEC isn’t handling crypto regulation ‘strategically’ | TechCrunch','As developers turn their gears in the crypto world, regulatory uncertainty is casting a shadow over the work they’re doing.','https://techcrunch.com/2023/09/22/chris-lehane-crypto-regulations/','https://techcrunch.com/wp-content/uploads/2023/09/53203224992_ceaa387ca4_k-1.jpg?resize=1200,800','2023-09-22T14:01:02Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Kate Park','Niura''s EEG-implemented earbuds scan your brain health and recommend music to your mood','Niura has developed a pair of earbuds that monitor brain activity and, it claims, can both watch for potential health issues and match music to a user''s mood...','https://techcrunch.com/2023/09/22/niuras-eeg-implemented-earbuds-scan-your-brain-health-and-recommend-music-to-your-mood/','https://s.yimg.com/ny/api/res/1.2/zb56dhlMekSGuvfjZZjvJw--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD0xMjAw/https://media.zenfs.com/en/techcrunch_350/ea10db4295261a9657627687dfa96b5c','2023-09-22T13:20:29Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Natasha Lomas','Intel (re)fined $400M by EU for ''naked restrictions'' dating back to the noughties | TechCrunch','Talk about old news: The European Union has reimposed a fine (totalling €376.36 million) on Intel for antitrust violations dating back decades. Veteran The European Union has reimposed a fine (totalling €376.36 million) on Intel for antitrust violations datin…','https://techcrunch.com/2023/09/22/intel-refined-in-eu-antitrust-sage/','https://techcrunch.com/wp-content/uploads/2017/11/gettyimages-836626196.jpg?resize=1200,800','2023-09-22T12:20:49Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Ivan Mehta','Amazon Prime Video will start showing ads from early next year | TechCrunch','After Netflix and Disney+ introduced ad-supported plans last year, Amazon said in an update today that it will start showing ads on Prime Video early next','https://techcrunch.com/2023/09/22/amazon-prime-video-will-start-showing-ads-from-early-next-year/','https://techcrunch.com/wp-content/uploads/2022/10/GettyImages-1242123707.jpg?resize=1200,767','2023-09-22T11:44:01Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Annie Njanja','South Africa''s FinanceGPT simplifies financial analysis, set to interface in local languages','FinanceGPT is a generative AI startup built to help companies in their financial analysis tasks.  Initially built for startups without in-house finance teams...','https://techcrunch.com/2023/09/22/financegpt-generative-ai-tools-for-financial-analysis/','https://s.yimg.com/ny/api/res/1.2/lO_y.Vl65q68gsj2pcr1Ig--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD03MTA-/https://media.zenfs.com/en/techcrunch_350/6dae1c4150dab466e4f14ab64235c216','2023-09-22T11:34:39Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Ivan Mehta','Threads adds easy profile switching to its mobile apps | TechCrunch','Meta-owned Twitter rival Threads has finally added a way to switch between multiple accounts without logging out.','https://techcrunch.com/2023/09/22/threads-adds-easy-profile-switching-to-its-mobile-apps/','https://techcrunch.com/wp-content/uploads/2023/07/Threads-GettyImages-1524134312.jpg?resize=1200,800','2023-09-22T08:30:46Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Ivan Mehta','X is shutting down its Circle feature in October | TechCrunch','Elon Musk-owned X, formerly Twitter, is shutting down its Circle feature, which allowed users to share a post only with a set of people','https://techcrunch.com/2023/09/21/x-is-shutting-down-its-circle-feature-in-october/','https://techcrunch.com/wp-content/uploads/2023/08/twitter-x-musk-graffiti.jpg?resize=1200,675','2023-09-22T04:16:38Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Kate Park','Plantiga Technologies'' AI-powered footwear sensor pod aims to reduce injury risks | TechCrunch','Plantiga Technologies, a Vancouver-based movement analytics company, wants to help people improve rehabilitation and reduce injury risks through an Plantiga Technologies has built an AI-powered sensor pod that could embedded in footwear and software to help u…','https://techcrunch.com/2023/09/21/plantiga-technologies-ai-powered-footwear-sensor-pod-aims-to-reduce-injury-risks/','https://techcrunch.com/wp-content/uploads/2023/09/PLANTIGA-FINALS-DAY2-3-emble-119-1.jpg?resize=1200,800','2023-09-22T02:16:59Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Kate Park','HME Square aims to measure glucose painlessly with photoacoustics | TechCrunch','People with diabetes have to monitor their blood sugar levels regularly by pricking their skin. Many glucose-monitoring device makers worldwide are','https://techcrunch.com/2023/09/21/hme-square-aims-to-measure-glucose-painlessly-with-photoacoustics/','https://techcrunch.com/wp-content/uploads/2023/09/Smart-Watch.FQ-View-2-1.png?resize=1017,1200','2023-09-22T01:24:59Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Taylor Hatmaker','TikTok may start serving you Google Search results | TechCrunch','TikTok is experimenting with adding Google Search into its own in-app search results.','https://techcrunch.com/2023/09/21/tiktok-may-start-serving-you-google-search-results/','https://techcrunch.com/wp-content/uploads/2023/03/GettyImages-1248373545.jpg?resize=1200,788','2023-09-22T00:20:49Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Taylor Hatmaker','What we learned from Microsoft''s big Xbox leak | TechCrunch','Microsoft accidentally leaked a trove of juicy documents revealing details on its Xbox business and industry strategy.','https://techcrunch.com/2023/09/21/microsoft-xbox-leak-ftc/','https://techcrunch.com/wp-content/uploads/2016/06/e3_2016-6130028.jpg?resize=1200,755','2023-09-21T23:12:35Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Neesha A. Tambe','And the winner of Startup Battlefield at Disrupt 2023 is… BioticsAI | TechCrunch','The winner BioticsAI has built an AI-based platform that plugs into an ultrasound machine to prevent fetal malformation misdiagnosis.','https://techcrunch.com/2023/09/21/startup-battlefield-winner-techcrunch-disrupt-2023/','https://techcrunch.com/wp-content/uploads/2023/09/DSC02580.jpg?resize=1200,800','2023-09-21T22:45:56Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Christine Hall','eStreamly blends physical, digital shopping with the video as the star | TechCrunch','eStreamly offers business-to-business video commerce software to enable livestreams and videos to be shoppable across platforms.','https://techcrunch.com/2023/09/21/estreamly-livestream-shopping-battlefield/','https://techcrunch.com/wp-content/uploads/2023/09/IMG_1100-2.jpeg?resize=1200,675','2023-09-21T21:54:10Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Paul Sawers','Salesforce to acquire Airkit.ai, a low-code platform for building AI customer service agents | TechCrunch','Salesforce is to acquire Airkit.ai, a low-code platform that helps ecommerce companies build AI-powered customer service agents.','https://techcrunch.com/2023/09/21/salesforce-airkit/','https://techcrunch.com/wp-content/uploads/2023/09/feat-e1695328683148.png?w=1120','2023-09-21T21:35:42Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Christine Hall','AvantGuard wants to turn chlorine into the best antiseptic you’ve ever seen | TechCrunch','AvantGuard is making a polymer version of chlorine-based disinfectants that can create antimicrobial surfaces.','https://techcrunch.com/2023/09/21/avantguard-chlorine-antiseptic-battlefield/','https://techcrunch.com/wp-content/uploads/2023/09/PXL_20230920_221725609.jpg?resize=1200,675','2023-09-21T21:17:35Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Kyle Wiggers','Meredith Whittaker reaffirms that Signal would leave U.K. if forced by privacy bill | TechCrunch','Meredith Whittaker, the president of the Signal Foundation, the organization that maintains the Signal messaging app, spoke about the U.K.''s controversial new privacy bill at TC Disrupt 2023.','https://techcrunch.com/2023/09/21/meredith-whittaker-reaffirms-that-signal-would-leave-u-k-if-forced-by-privacy-bill/','https://techcrunch.com/wp-content/uploads/2023/09/whittaker-vs-whittaker.jpg?resize=1200,675','2023-09-21T20:50:32Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Aisha Malik','OnePlus confirms its first foldable is officially ''coming soon'' | TechCrunch','OnePlus is officially gearing up to launch its first foldable phone "soon," the company told TechCrunch on Thursday.','https://techcrunch.com/2023/09/21/oneplus-confirms-its-first-foldable-is-officially-coming-soon/','https://techcrunch.com/wp-content/uploads/2023/02/20230228_145824.jpg?resize=1200,900','2023-09-21T20:39:53Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Christine Hall','Don’t want that commuter stipend? Bundl enables employees to choose their own company benefits | TechCrunch','Don’t want that commuter stipend? Bundl enables employees to choose their own company benefits | TechCrunchtechcrunch.com','https://techcrunch.com/2023/09/21/bundl-employee-benefits-battlefield/','https://techcrunch.com/wp-content/uploads/2023/09/PXL_20230920_155849668.jpg?resize=1200,675','2023-09-21T20:05:30Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Harri Weber','AppCyclers wants to fight e-waste pollution across Africa | TechCrunch','Ghana-based startup AppCyclers is tackling e-waste pollution in Africa via an online marketplace and local collection programs.','https://techcrunch.com/2023/09/21/appcyclers-wants-to-fight-e-waste-pollution-across-africa/','https://techcrunch.com/wp-content/uploads/2023/09/WhatsApp-Image-2021-07-16-at-6.50.32-AM.webp?w=1024','2023-09-21T19:42:45Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Rita Liao','GGV splits off China business following congressional panel probe','GGV, the 23-year-old U.S. venture capital firm with a storied track record in China, is splitting into two branches as escalating geopolitical tensions...','https://techcrunch.com/2023/09/21/ggv-splits-off-china-business-following-congressional-panel-probe/','https://s.yimg.com/ny/api/res/1.2/Iaw6UFfIy50SmglzngJs2Q--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD04MDA-/https://media.zenfs.com/en/techcrunch_350/798778a12cbb0c61f42666de1a5d4862','2023-09-21T19:37:42Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Kyle Wiggers','The copyright issues around generative AI aren''t going away anytime soon | TechCrunch','At Disrupt 2023, one of the co-founders of Runway, Anastasis Germanidis, said that his company is considering ways to tackle the challenges around copyright and generative AI.','https://techcrunch.com/2023/09/21/the-copyright-issues-around-generative-ai-arent-going-away-anytime-soon/','https://techcrunch.com/wp-content/uploads/2023/09/53202681227_9073c8f3dc_k.jpg?resize=1200,800','2023-09-21T19:30:25Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Carly Page','Kindo aims to take the security stress out of AI workflows | TechCrunch','Ron Williams, co-founder and CEO of Kindo, knows a thing or two about cybersecurity, having previously led security teams at League of Legends developer','https://techcrunch.com/2023/09/21/kindo-aims-to-take-the-security-stress-out-of-ai-workflows/','https://techcrunch.com/wp-content/uploads/2023/09/Kindo-team.jpg?resize=1200,968','2023-09-21T19:07:26Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Jacquelyn Melinek','Here’s the crypto news you missed at Disrupt 2023 | TechCrunch','Welcome back to Chain Reaction. This week I’ve been in San Francisco for TechCrunch Disrupt 2023. It''s been a three-day journey ja- packed with panels, booths and conversations around tech, AI, space, security and of course, crypto.','https://techcrunch.com/2023/09/21/heres-the-crypto-news-you-missed-at-disrupt-2023/','https://techcrunch.com/wp-content/uploads/2023/09/53200250616_8bd2b3f4fe_o.jpg?resize=1200,800','2023-09-21T19:00:15Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Brian Heater','Firebot is designed to scout burning builders before sending in firefighters | TechCrunch','Austin-based Paradigm Robotics built Firebot to scout the inside of burning buildings before sending in firefighters.','https://techcrunch.com/2023/09/21/firebot-is-designed-to-scout-burning-builders-before-sending-in-firefighters/','https://techcrunch.com/wp-content/uploads/2023/09/73B1888A-800C-4723-94AF-D09F59A1F6EE.jpeg?resize=1200,900','2023-09-21T18:27:50Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Rita Liao','Roblox cuts 30 on talent acquisition team as hiring slows | TechCrunch','Roblox, the community-focused gaming platform popular amongst kids, has downsized a substantial portion of its talent acquisition team, signaling a shift','https://techcrunch.com/2023/09/21/roblox-cuts-30-on-talent-acquisition-team-as-hiring-slows/','https://techcrunch.com/wp-content/uploads/2023/08/roblox-mobile.jpg?w=1024','2023-09-21T18:21:31Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Brian Heater','Diligent raises $25 million to triple its nursing robot’s reach','As hospitals overflowed, staff was forced to take on impossible long shifts, risking their own health in the process.  In many ways, it was the perfect...','https://techcrunch.com/2023/09/21/diligent-raises-25-million-to-triple-its-nursing-robots-reach/','https://s.yimg.com/ny/api/res/1.2/FArG5HCzWZK2tgAbL7JoWw--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD04NzQ-/https://media.zenfs.com/en/techcrunch_350/e95b43c0378d425a836e397f79749018','2023-09-21T18:00:50Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Christine Hall','Former a16z execs launch Bastion | TechCrunch','Bastion launched a suite of products so companies can integrate web3 infrastructure into their existing enterprise technologies.','https://techcrunch.com/2023/09/21/former-a16z-execs-launch-bastion-crypto/','https://techcrunch.com/wp-content/uploads/2023/01/GettyImages-AA046815.jpg?resize=1200,669','2023-09-21T17:58:14Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Haje Jan Kamps','Banish cumulative graphs from your pitch deck | TechCrunch','Investors want to see accelerating growth, and that is much harder to read on a cumulative graph.','https://techcrunch.com/2023/09/21/no-cumulative-numbers/','https://techcrunch.com/wp-content/uploads/2023/09/20230920-IMG_5958.jpg?resize=1200,900','2023-09-21T17:30:58Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Aria Alamalhodaei','Frontier Space Technologies is developing an on-orbit autonomous lab to make space science easy | TechCrunch','Astronauts have been conducting experiments on the International Space Station for as long as the station has been in orbit, but astronaut labor is','https://techcrunch.com/2023/09/21/frontier-space-technologies-is-developing-an-on-orbit-autonomous-lab-to-make-space-science-easy/','https://techcrunch.com/wp-content/uploads/2020/02/GettyImages-1128316743.jpg?w=789','2023-09-21T17:27:04Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Kyle Wiggers','How generative AI is accelerating disinformation | TechCrunch','Panelists at TC Disrupt 2023 spoke about the ways in which generative AI is accelerating the spread of disinformation.','https://techcrunch.com/2023/09/21/how-generative-ai-is-accelerating-disinformation/','https://techcrunch.com/wp-content/uploads/2023/09/53202358557_3c8ce7f19d_k.jpg?resize=1200,800','2023-09-21T17:15:53Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Kyle Wiggers','Windows 11 gains support for managing passkeys | TechCrunch','Windows 11 has gained support for passkeys, the digital credentials that can be used as an authentication method for websites and apps.','https://techcrunch.com/2023/09/21/windows-11-gains-support-for-managing-passkeys/','https://techcrunch.com/wp-content/uploads/2021/06/windows11.jpg?resize=1200,654','2023-09-21T17:14:13Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Lauren Forristal','AI startup Gizmo raises $3.5M by using gamified quizzes and flashcards to make learning fun | TechCrunch','Gizmo, a generative AI learning startup that uses gamified quizzes to engage learners, raised $3.5 million in seed funding.','https://techcrunch.com/2023/09/21/ai-startup-gizmo-funding-gamified-quizzes-flashcards-make-learning-fun/','https://techcrunch.com/wp-content/uploads/2023/08/GettyImages-1491414597.jpg?resize=1200,900','2023-09-21T16:56:42Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Jonathan Martinez','How to spend your first $10K on paid ads | TechCrunch','In the early days of your startup, it’s important to be as efficient as possible, not only with this $10K budget, but also with your time.','https://techcrunch.com/2023/09/21/how-to-spend-your-first-10k-on-paid-ads/','https://techcrunch.com/wp-content/uploads/2023/09/GettyImages-1186939630.jpg?resize=1200,800','2023-09-21T16:45:22Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Natasha Lomas','UK bolts US ''data bridge'' deal onto EU-US Data Privacy Framework | TechCrunch','The UK government has officially confirmed it will piggyback on a transatlantic data transfer deal between the European Union and the US by bolting on an The UK government has officially confirmed it will piggyback on a transatlantic data transfer deal betwee…','https://techcrunch.com/2023/09/21/uk-us-data-bridge/','https://techcrunch.com/wp-content/uploads/2023/05/GettyImages-1488626313.jpg?resize=1200,800','2023-09-21T16:43:28Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Manish Singh','Saregama eyes Pocket Aces acquisition in video push | TechCrunch','Saregama is in talks to acquire Pocket Aces, three people familiar with the matter said, as the oldest Indian music label grows its video ambitions. The Saregama is in talks to acquire the Bengaluru-headquartered Pocket Aces as the oldest Indian music label e…','https://techcrunch.com/2023/09/21/saregama-pocket-aces/','https://techcrunch.com/wp-content/uploads/2019/10/GettyImages-1158428016.jpg?resize=1200,800','2023-09-21T16:33:26Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Rebecca Bellan','Cruise would join the call to ban human drivers in city centers, says CEO | TechCrunch','Cruise co-founder and CEO Kyle Vogt posed a controversial question at TechCrunch Disrupt 2023: At what point does it still make sense to have human-driven','https://techcrunch.com/2023/09/21/cruise-would-join-the-call-to-ban-human-drivers-in-city-centers-says-ceo/','https://techcrunch.com/wp-content/uploads/2023/09/GettyImages-1692833223.jpg?w=1200','2023-09-21T16:27:01Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Mary Ann Azevedo','Facebook rolls out multiple personal profiles feature','Facebook will now allow users to create multiple personal profiles in an effort to help users feel “freer” to engage on the platform, the company announced today. The move makes sense, so much so that one wonders what took the company so long to roll it out. …','https://techcrunch.com/2023/09/21/facebook-rolls-out-multiple-personal-profiles-feature/','https://techcrunch.com/wp-content/uploads/2023/09/Additional-Facebook-Profiles_Header.jpeg?resize=1200,675','2023-09-21T16:14:46Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Sarah Perez','Snapchat now has over 5 million paying users for Snapchat+ | TechCrunch','Snapchat announced today its subscription service for power users, Snapchat+ has now topped 5 million subscribers -- a figure that''s up from 4 million in','https://techcrunch.com/2023/09/21/snapchat-now-has-over-5-million-paying-users-for-snapchat/','https://techcrunch.com/wp-content/uploads/2023/09/Screenshot-2023-09-21-at-11.24.34-AM.jpg?resize=1200,675','2023-09-21T15:45:14Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Sarah Perez','Mastodon’s latest release makes the open source Twitter alternative easier to use','As changes at Elon Musk’s X continue to push former Twitter users to seek alternatives, the open-sourced, decentralized social network Mastodon — a popular Twitter/X rival — is releasing an update designed to make it easier for users to get started, use its n…','https://techcrunch.com/2023/09/21/mastodons-latest-release-makes-the-open-source-twitter-alternative-easier-to-use/','https://techcrunch.com/wp-content/uploads/2023/05/hero.jpg?resize=1200,734','2023-09-21T15:00:13Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Sarah Perez','YouTube debuts a new app, YouTube Create for editing videos, adding effects and more | TechCrunch','YouTube this morning introduced a new app for creators, YouTube Create, that will offer a suite of easy-to-use and free tools that will allow them to make','https://techcrunch.com/2023/09/21/youtube-debuts-a-new-app-youtube-create-for-editing-videos-adding-effects-and-more/','https://techcrunch.com/wp-content/uploads/2023/09/Screenshot-2023-09-21-at-10.50.13-AM.jpg?w=1186','2023-09-21T14:53:15Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Lauren Forristal','YouTube Studio to give creators a generative AI tool to suggest video topics | TechCrunch','During today''s YouTube event, CEO Neal Mohan revealed that the platform is testing a new generative AI-powered tool in YouTube Studio that suggests video YouTube is testing a new generative AI-powered tool in YouTube Studio that suggests video topics.','https://techcrunch.com/2023/09/21/youtube-studio-to-give-creators-a-generative-ai-tool-to-suggest-video-topics/','https://techcrunch.com/wp-content/uploads/2023/09/Screenshot-2023-09-21-at-10.29.03-AM-2.png?w=1170','2023-09-21T14:50:56Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Sarah Perez','YouTube to add AI creator tools to find music for videos, add dubs | TechCrunch','YouTube is expanding its Creator Music feature, announced last year, with new AI features in addition to the launch of an AI-dubbing tool. Currently,','https://techcrunch.com/2023/09/21/youtube-to-add-ai-creator-tools-to-find-music-for-videos-add-dubs/','https://techcrunch.com/wp-content/uploads/2023/09/Screenshot-2023-09-21-at-10.29.35-AM.jpg?resize=1200,654','2023-09-21T14:39:33Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Sarah Perez','YouTube Shorts to gain a generative AI feature called Dream Screen | TechCrunch','YouTube today announced a new feature coming to its short-form video platform Shorts that will allow users to leverage AI tools to create videos. The','https://techcrunch.com/2023/09/21/youtube-shorts-to-gain-a-generative-ai-feature-called-dream-screen/','https://techcrunch.com/wp-content/uploads/2023/09/dream-screen.jpg?resize=1200,699','2023-09-21T14:25:55Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Ron Miller','Cisco to acquire Splunk in $28B mega deal | TechCrunch','Cisco entered the world of mega deals today when it announced it intends to acquire Splunk for a hefty $28 billion.','https://techcrunch.com/2023/09/21/cisco-to-acquire-splunk-in-28b-mega-deal/','https://techcrunch.com/wp-content/uploads/2023/09/GettyImages-1601469961.jpg?w=1024','2023-09-21T13:43:16Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Kyle Wiggers','Mesh, which helps people manage their digital assets, raises $22M | TechCrunch','Mesh (formerly Front Finance), a startup developing a service to help customers transfer and manage digital assets like crypto, has raised $22 million in','https://techcrunch.com/2023/09/21/mesh-which-helps-people-manage-their-digital-assets-raises-22m/','https://techcrunch.com/wp-content/uploads/2022/02/GettyImages-1281179480.jpg?resize=1200,800','2023-09-21T13:01:16Z');
INSERT INTO article(name,author,title,description,url,urlToImage,publishedAt) VALUES ('TechCrunch','Frederic Lardinois','Harness launches Gitness, an open-source GitHub competitor | TechCrunch','Since its launch in 2017, Harness, the software delivery platform founded by AppDynamics co-founder and CEO Jyoti Bansal, expanded from being continuous','https://techcrunch.com/2023/09/21/oh-gitness-harness-launches-gitness-an-open-source-github-competitor/','https://techcrunch.com/wp-content/uploads/2018/05/gettyimages-465410412.jpg?resize=1200,802','2023-09-21T13:00:54Z');
